# Generated by Django 2.2.7 on 2019-11-08 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Encontro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('tema', models.CharField(blank=True, max_length=30, null=True)),
                ('local', models.CharField(blank=True, max_length=30, null=True)),
                ('dt_ini', models.DateField(blank=True, null=True)),
                ('dt_fim', models.DateField(blank=True, null=True)),
                ('desc', models.CharField(blank=True, max_length=70, null=True)),
                ('cep', models.IntegerField(blank=True, null=True)),
                ('logradouro', models.CharField(blank=True, max_length=60, null=True)),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('complemento', models.CharField(blank=True, max_length=40, null=True)),
                ('bairro', models.CharField(blank=True, max_length=40, null=True)),
                ('localidade', models.CharField(blank=True, max_length=60, null=True)),
                ('uf', models.CharField(blank=True, max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_conv', models.CharField(choices=[('c', 'Enviado'), ('r', 'Recusado'), ('d', 'Desistiu'), ('a', 'Aceito'), ('s', 'SemRetornoouContato')], max_length=30, verbose_name='Status:')),
                ('nome_equipe', models.CharField(choices=[('animacao', 'Animação'), ('canto', 'canto'), ('compras', 'Compras'), ('cozinha', 'Cozinha'), ('circulo', 'Círculo'), ('co_gerais', 'Coord.Gerais'), ('dirigentes', 'Dirigentes'), ('espirit', 'Espiritualizador'), ('interc', 'Intercessão'), ('lanche', 'Lanche'), ('faxina', 'FaxinaeLimpeza'), ('sala', 'Sala'), ('secretaria', 'Secretaria'), ('transito', 'OrdemeTrânsito'), ('visitação', 'Visitação')], max_length=30, verbose_name='Equipes:')),
                ('obs', models.CharField(blank=True, max_length=60, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paroquia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_paroquia', models.CharField(max_length=30)),
                ('regiao', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('sobrenome', models.CharField(max_length=70)),
                ('apelido', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='')),
                ('dt_nasc', models.DateField(blank=True, null=True)),
                ('nivel', models.CharField(choices=[('dir_espiritual', 'DiretorEspiritual'), ('coord', 'CoordenadorGeral'), ('coord_equipe', 'CoordenadordeEquipe'), ('dirigente', 'Dirigente'), ('servo', 'Servo'), ('convidado', 'Convidado')], max_length=30, verbose_name='Nível:')),
                ('encontrista', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], max_length=1, verbose_name='Encontrista?')),
                ('cep', models.IntegerField()),
                ('logradouro', models.CharField(max_length=60)),
                ('numero', models.IntegerField()),
                ('complemento', models.CharField(max_length=40)),
                ('bairro', models.CharField(max_length=40)),
                ('localidade', models.CharField(max_length=60)),
                ('uf', models.CharField(max_length=2)),
                ('_dtcriacao', models.DateField(auto_now_add=True)),
                ('_deleted', models.CharField(blank=True, max_length=1, null=True)),
                ('paroquia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='montagem.Paroquia')),
            ],
            options={
                'verbose_name': 'Servo',
                'verbose_name_plural': 's',
            },
        ),
    ]
