# Generated by Django 2.2.7 on 2019-11-10 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('montagem', '0002_auto_20191109_2112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='_dtcriacao',
            new_name='dtcriacao',
        ),
    ]
