# Generated by Django 2.2.7 on 2019-11-14 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('montagem', '0003_auto_20191109_2228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='_deleted',
        ),
        migrations.AddField(
            model_name='person',
            name='obs',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='status',
            field=models.BooleanField(default=True, editable=False),
        ),
    ]
