# Generated by Django 2.2.7 on 2019-11-15 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('montagem', '0004_auto_20191113_2111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='encontrista',
        ),
        migrations.AlterField(
            model_name='person',
            name='nivel',
            field=models.CharField(choices=[('dir_espiritual', 'Diretor Espiritual'), ('coord', 'Coordenador Geral'), ('coord_equipe', 'Coordenador de Equipe'), ('dirigente', 'Dirigente'), ('servo', 'Servo'), ('convidado', 'Convidado')], max_length=30, verbose_name='Nível:'),
        ),
    ]
