# Generated by Django 2.2.7 on 2019-11-15 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('montagem', '0005_auto_20191115_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='nivel',
            field=models.CharField(choices=[('dir_espiritual', 'Diretor Espiritual'), ('coord', 'Coordenador Geral'), ('coord_equipe', 'Coordenador de Equipe'), ('dirigente', 'Dirigente'), ('servo', 'Servo'), ('convidado', 'Convidado'), ('encontrista', 'Encontrista')], max_length=30, verbose_name='Nível:'),
        ),
    ]
