# Generated by Django 2.2.7 on 2019-11-15 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('montagem', '0006_auto_20191115_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='tel1',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='tel2',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
