# Generated by Django 2.2.7 on 2019-11-18 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('montagem', '0007_auto_20191115_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipe',
            name='encontros',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='montagem.Encontro'),
        ),
        migrations.AddField(
            model_name='equipe',
            name='servos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='montagem.Person'),
        ),
        migrations.AlterField(
            model_name='person',
            name='nivel',
            field=models.CharField(blank=True, choices=[('dir_espiritual', 'Diretor Espiritual'), ('coord', 'Coordenador Geral'), ('coord_equipe', 'Coordenador de Equipe'), ('dirigente', 'Dirigente'), ('servo', 'Servo'), ('convidado', 'Convidado'), ('encontrista', 'Encontrista')], max_length=30, verbose_name='Nível:'),
        ),
        migrations.AlterField(
            model_name='person',
            name='paroquia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='montagem.Paroquia'),
        ),
    ]
