# Generated by Django 2.2.7 on 2019-11-18 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('montagem', '0009_auto_20191118_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipe',
            name='encontros',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='montagem.Encontro'),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='servos',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='montagem.Person'),
        ),
    ]
