# Generated by Django 2.2.7 on 2019-11-20 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('montagem', '0012_auto_20191120_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='paroquia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='montagem.Paroquia'),
        ),
    ]
