# Generated by Django 2.2.7 on 2019-11-21 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('montagem', '0013_auto_20191120_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='tel1',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
