# Generated by Django 2.2.7 on 2019-11-21 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('montagem', '0015_auto_20191120_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='dt_nasc',
            field=models.DateField(blank=True, default=' __/__/___ ', null=True),
        ),
    ]
