# Generated by Django 2.2.7 on 2019-12-01 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('montagem', '0018_auto_20191201_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('animacao', 'Animação'), ('canto', 'canto'), ('compras', 'Compras'), ('cozinha', 'Cozinha'), ('circulo', 'Círculo'), ('co_gerais', 'Coord.Gerais'), ('dirigentes', 'Dirigentes'), ('espirit', 'Espiritualizador'), ('interc', 'Intercessão'), ('lanche', 'Lanche'), ('faxina', 'FaxinaeLimpeza'), ('sala', 'Sala'), ('secretaria', 'Secretaria'), ('transito', 'OrdemeTrânsito'), ('visitação', 'Visitação')], max_length=30, verbose_name='Equipes:')),
                ('obs', models.CharField(blank=True, max_length=60, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Membros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_convite', models.DateField()),
                ('status_conv', models.CharField(choices=[('e', 'Convite Enviado'), ('r', 'Convite Recusado'), ('d', 'Desistiu'), ('a', 'Aceito'), ('s', 'Sem Retorno')], default='Aguardando Convite', max_length=1, verbose_name='Status:')),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='montagem.Equipe')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='montagem.Person')),
            ],
        ),
        migrations.RemoveField(
            model_name='group',
            name='members',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='group',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='person1',
        ),
        migrations.DeleteModel(
            name='Convite',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='Membership',
        ),
        migrations.DeleteModel(
            name='Person1',
        ),
        migrations.AddField(
            model_name='equipe',
            name='membs',
            field=models.ManyToManyField(through='montagem.Membros', to='montagem.Person'),
        ),
    ]
