# Generated by Django 2.2.7 on 2019-12-01 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('montagem', '0020_auto_20191201_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipe',
            name='ano',
            field=models.IntegerField(default=2019),
            preserve_default=False,
        ),
    ]
