# Generated by Django 2.2.7 on 2019-12-02 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('montagem', '0022_auto_20191202_1233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipe',
            name='membs',
        ),
        migrations.AlterField(
            model_name='equipe',
            name='nome_equipe',
            field=models.CharField(choices=[('animacao', 'Animação'), ('espera', 'Espera'), ('canto', 'Canto'), ('compras', 'Compras'), ('cozinha', 'Cozinha'), ('circulo', 'Círculo'), ('co_gerais', 'Coord.Gerais'), ('dirigentes', 'Dirigentes'), ('espirit', 'Espiritualizador'), ('interc', 'Intercessão'), ('lanche', 'Lanche'), ('faxina', 'Faxina e Limpeza'), ('sala', 'Sala'), ('secretaria', 'Secretaria'), ('transito', 'Ordem e Trânsito'), ('visitação', 'Visitação')], max_length=30, verbose_name='Equipes:'),
        ),
    ]
