# Generated by Django 2.2.7 on 2019-12-02 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('montagem', '0025_auto_20191202_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membros',
            name='equipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='montagem.Equipe'),
        ),
    ]
