# Generated by Django 2.2.7 on 2019-12-18 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('montagem', '0026_auto_20191202_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipe',
            name='membs',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='montagem.Person'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='cep',
            field=models.CharField(max_length=8),
        ),
    ]
