# Generated by Django 2.2.7 on 2019-12-19 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('montagem', '0027_auto_20191217_2339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipe',
            name='membs',
        ),
    ]
