# Generated by Django 2.2.7 on 2019-12-23 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('montagem', '0028_remove_equipe_membs'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='idade',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='membros',
            name='status_conv',
            field=models.CharField(choices=[('ac', 'Aguardando Convite'), ('e', 'Convite Enviado'), ('r', 'Convite Recusado'), ('d', 'Desistiu'), ('a', 'Aceito'), ('s', 'Sem Retorno')], default='Aguardando Convite', max_length=1, verbose_name='Status:'),
        ),
    ]
