# Generated by Django 2.2.7 on 2020-01-19 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('montagem', '0029_auto_20191223_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membros',
            name='equipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipe', to='montagem.Equipe'),
        ),
        migrations.AlterField(
            model_name='membros',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='person', to='montagem.Person'),
        ),
    ]
