# Generated by Django 2.2.7 on 2020-01-21 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('montagem', '0030_auto_20200119_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('casado', 'Casado'), ('solteiro', 'Solteiro')], max_length=8, null=True),
        ),
    ]
